### ISSUE TITLE
'

### ISSUE THREAD

**Issue by it-is-wednesday** [omrisim210/anti-smoking#1]
כותרת

**Comment by ohmree** [comment]
לעשן זה
# גיי

**Comment by ohmree** [comment]
בסוף לא הוספתי פה כלום אבל אני עדיין מתנגד לעישון של סיגריות במיוחד ושל כל דבר בוער/מעשן בפרט :smiley:

**Comment by it-is-wednesday** [comment]
איך מוחקים

**Comment by it-is-wednesday** [comment]
שחרר
